# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.rbenv/shims:$HOME/.local/bin:$HOME/bin:$HOME/.rbenv/bin

export PATH

eval "$(rbenv init -)"
