---
- hosts: 192.168.56.102
  tasks:
    - name: download rbenv from github
      get_url:
        url: https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer
        dest: /tmp/rbenv-installer
        mode: 0755
    - name: install rbenv, ruby 2.5.1, and rails latest 
      become: yes
      become_method: su 
      become_flags: ' -'
      become_user: nath
      command: "{{ item }}"
      with_items:
        - bash -lc "/tmp/rbenv-installer"
        - bash -lc "rbenv install 2.5.1"
        - bash -lc "rbenv local 2.5.1;gem install rails"
